valor = input("Digite alguma coisa: ")
print("O valor tem numero ?  ",valor.isnumeric())
print("O valor tem letra?  ",valor.isalpha())
print("O valor tem letra maiscula? ",valor.isupper())
print("O valor tem letra minuscula? ",valor.islower())
print("O valor é um alpha numerico? ",valor.isalnum())
print("É um espaço? ",valor.isspace())
print("O valor tem sprint? ",valor.isprintable())